### ISSUE TITLE
Business Solution add button 

### ISSUE THREAD

**Issue by NanaRei** [InfoSecDecoded/InfoSec-Decodedv2.0#4]
Current section 
![business solution](https://user-images.githubusercontent.com/32437556/60819689-e30b3c80-a154-11e9-84dd-8719a5ae24e6.png)

Underneath put a "Request a Consultation" 

Example of "Request Consultation" 
![Request Consultation](https://user-images.githubusercontent.com/32437556/60820919-544bef00-a157-11e9-9018-72417d71009b.png)

Choose one suggested solution: 
1. directs them to the footer where we have our contact information, OR 
2. directs you to another webpage with a form (from Cylance.com), OR
Example of Request for Consultation form
![Request a Consultation form](https://user-images.githubusercontent.com/32437556/60820737-ea334a00-a156-11e9-8bcb-9977e308ea87.png)

3. automatically opens an email message 
Example email message 
![Automatically opens an email message](https://user-images.githubusercontent.com/32437556/60821238-fa97f480-a157-11e9-861d-deba843c13e8.png)

The easiest solution is #1 due to time. For the next version of the website, we will consider #2, #3 and other solutions.

**Comment by NanaRei** [comment]
Change "Business Solution" to "Solutions"

**Comment by NanaRei** [comment]
Current view. 
![consultation feature](https://user-images.githubusercontent.com/32437556/60938358-8741d000-a288-11e9-9665-2069c923fd67.png)

The font size for the "Request a Consultation" and the button is taking away from the above topics. 
1. Make the font size smaller and less noticeable. This is drawing your eyes away from the "Solutions"
2. Choose either the paper airplane or the button. Having both is distracting to the eye. 
3. Change the color of the button to the same color blue that was used for the "login" button and resize the button. - OR- you can use a blue arrow instead of a button. See the image above for reference.

**Comment by sunschong** [comment]
![consult button](https://user-images.githubusercontent.com/35852811/61179896-6dbec200-a5c1-11e9-8864-46ff304b0c7c.JPG)

1. Make it a round button.
2. Font size is still too big. I would make "Request a Consultation" smaller.
3. Experiment with different fonts in the future.
