### ISSUE TITLE
Change to "Team Members" 

### ISSUE THREAD

**Issue by NanaRei** [InfoSecDecoded/InfoSec-Decodedv2.0#9]
Current "Consulting Team" section
![Consulting Team](https://user-images.githubusercontent.com/32437556/60851408-e8de3d80-a1a7-11e9-8b74-8c4f8f51dfb7.png)

1. Change "Consulting Team" to "Team Members"
2. Remove email addresses from the bios. 
3. Adjust the size of the boxes around the photos and the font size in the profile pop out box

![profile pop out box](https://user-images.githubusercontent.com/32437556/60851500-3f4b7c00-a1a8-11e9-92a1-97e52a01e006.png)

**Comment by sunschong** [comment]
Updated font size in pop up:
![profile pop up font update](https://user-images.githubusercontent.com/35852811/61073474-61244900-a3ca-11e9-9e03-d91e2a0f79b7.JPG)

**Comment by NanaRei** [comment]
Outstanding task: 
3. Adjust the size of the boxes: as of right now the box around Sam and Elizabeth's picture are different sizes
